// To use rest countries and display all the flags in the console

// initalize a xml http request

let xhr=new XMLHttpRequest();

//open a request and an url is passed to open methods

xhr.open("GET","https://restcountries.com/v2/all");

//process the request on the server side and retrieve the data

xhr.onload= function(){

    //please provide me data if my request lies in the range of status code 200-<300

    if(xhr.status>=200 && xhr.status<300){
        //provide data to server
        let data=JSON.parse(this.response);
        console.log(data);

//   for printing the flags of the country

    for(let i=0; i<data.length; i++){
        let user=data[i];
        console.log(`
        flags:${user.flags.svg}
        flags2:${user.flags.png}`)
        }
    }
}

//sending request to server

 xhr.send();

// output for displaying the flags

// httprequest.html:39 Live reload enabled.
// httprequest.js:18 Array(250)
// httprequest.js:23 
//         flags:https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg
//         flags2:https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ax.svg
//         flags2:https://flagcdn.com/w320/ax.png
// httprequest.js:23 
//         flags:https://flagcdn.com/al.svg
//         flags2:https://flagcdn.com/w320/al.png
// httprequest.js:23 
//         flags:https://flagcdn.com/dz.svg
//         flags2:https://flagcdn.com/w320/dz.png
// httprequest.js:23 
//         flags:https://flagcdn.com/as.svg
//         flags2:https://flagcdn.com/w320/as.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ad.svg
//         flags2:https://flagcdn.com/w320/ad.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ao.svg
//         flags2:https://flagcdn.com/w320/ao.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ai.svg
//         flags2:https://flagcdn.com/w320/ai.png
// httprequest.js:23 
//         flags:https://flagcdn.com/aq.svg
//         flags2:https://flagcdn.com/w320/aq.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ag.svg
//         flags2:https://flagcdn.com/w320/ag.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ar.svg
//         flags2:https://flagcdn.com/w320/ar.png
// httprequest.js:23 
//         flags:https://flagcdn.com/am.svg
//         flags2:https://flagcdn.com/w320/am.png
// httprequest.js:23 
//         flags:https://flagcdn.com/aw.svg
//         flags2:https://flagcdn.com/w320/aw.png
// httprequest.js:23 
//         flags:https://flagcdn.com/au.svg
//         flags2:https://flagcdn.com/w320/au.png
// httprequest.js:23 
//         flags:https://flagcdn.com/at.svg
//         flags2:https://flagcdn.com/w320/at.png
// httprequest.js:23 
//         flags:https://flagcdn.com/az.svg
//         flags2:https://flagcdn.com/w320/az.png
// httprequest.js:23 
//         flags:https://flagcdn.com/bs.svg
//         flags2:https://flagcdn.com/w320/bs.png
// httprequest.js:23 
//         flags:https://flagcdn.com/bh.svg
//         flags2:https://flagcdn.com/w320/bh.png
// httprequest.js:23 
//         flags:https://flagcdn.com/bd.svg
//         flags2:https://flagcdn.com/w320/bd.png
// httprequest.js:23 
//         flags:https://flagcdn.com/bb.svg
//         flags2:https://flagcdn.com/w320/bb.png
// httprequest.js:23 
//         flags:https://flagcdn.com/by.svg
//         flags2:https://flagcdn.com/w320/by.png
// httprequest.js:23 
//         flags:https://flagcdn.com/be.svg
//         flags2:https://flagcdn.com/w320/be.png
// httprequest.js:23 
//         flags:https://flagcdn.com/bz.svg
//         flags2:https://flagcdn.com/w320/bz.png
// httprequest.js:23 
//         flags:https://flagcdn.com/bj.svg
//         flags2:https://flagcdn.com/w320/bj.png
// httprequest.js:23 
//         flags:https://flagcdn.com/bm.svg
//         flags2:https://flagcdn.com/w320/bm.png
// httprequest.js:23 
//         flags:https://flagcdn.com/bt.svg
//         flags2:https://flagcdn.com/w320/bt.png
// httprequest.js:23 
//         flags:https://flagcdn.com/bo.svg
//         flags2:https://flagcdn.com/w320/bo.png
// httprequest.js:23 
//         flags:https://flagcdn.com/bq.svg
//         flags2:https://flagcdn.com/w320/bq.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ba.svg
//         flags2:https://flagcdn.com/w320/ba.png
// httprequest.js:23 
//         flags:https://flagcdn.com/bw.svg
//         flags2:https://flagcdn.com/w320/bw.png
// httprequest.js:23 
//         flags:https://flagcdn.com/bv.svg
//         flags2:https://flagcdn.com/w320/bv.png
// httprequest.js:23 
//         flags:https://flagcdn.com/br.svg
//         flags2:https://flagcdn.com/w320/br.png
// httprequest.js:23 
//         flags:https://flagcdn.com/io.svg
//         flags2:https://flagcdn.com/w320/io.png
// httprequest.js:23 
//         flags:https://flagcdn.com/um.svg
//         flags2:https://flagcdn.com/w320/um.png
// httprequest.js:23 
//         flags:https://flagcdn.com/vg.svg
//         flags2:https://flagcdn.com/w320/vg.png
// httprequest.js:23 
//         flags:https://flagcdn.com/vi.svg
//         flags2:https://flagcdn.com/w320/vi.png
// httprequest.js:23 
//         flags:https://flagcdn.com/bn.svg
//         flags2:https://flagcdn.com/w320/bn.png
// httprequest.js:23 
//         flags:https://flagcdn.com/bg.svg
//         flags2:https://flagcdn.com/w320/bg.png
// httprequest.js:23 
//         flags:https://flagcdn.com/bf.svg
//         flags2:https://flagcdn.com/w320/bf.png
// httprequest.js:23 
//         flags:https://flagcdn.com/bi.svg
//         flags2:https://flagcdn.com/w320/bi.png
// httprequest.js:23 
//         flags:https://flagcdn.com/kh.svg
//         flags2:https://flagcdn.com/w320/kh.png
// httprequest.js:23 
//         flags:https://flagcdn.com/cm.svg
//         flags2:https://flagcdn.com/w320/cm.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ca.svg
//         flags2:https://flagcdn.com/w320/ca.png
// httprequest.js:23 
//         flags:https://flagcdn.com/cv.svg
//         flags2:https://flagcdn.com/w320/cv.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ky.svg
//         flags2:https://flagcdn.com/w320/ky.png
// httprequest.js:23 
//         flags:https://flagcdn.com/cf.svg
//         flags2:https://flagcdn.com/w320/cf.png
// httprequest.js:23 
//         flags:https://flagcdn.com/td.svg
//         flags2:https://flagcdn.com/w320/td.png
// httprequest.js:23 
//         flags:https://flagcdn.com/cl.svg
//         flags2:https://flagcdn.com/w320/cl.png
// httprequest.js:23 
//         flags:https://flagcdn.com/cn.svg
//         flags2:https://flagcdn.com/w320/cn.png
// httprequest.js:23 
//         flags:https://flagcdn.com/cx.svg
//         flags2:https://flagcdn.com/w320/cx.png
// httprequest.js:23 
//         flags:https://flagcdn.com/cc.svg
//         flags2:https://flagcdn.com/w320/cc.png
// httprequest.js:23 
//         flags:https://flagcdn.com/co.svg
//         flags2:https://flagcdn.com/w320/co.png
// httprequest.js:23 
//         flags:https://flagcdn.com/km.svg
//         flags2:https://flagcdn.com/w320/km.png
// httprequest.js:23 
//         flags:https://flagcdn.com/cg.svg
//         flags2:https://flagcdn.com/w320/cg.png
// httprequest.js:23 
//         flags:https://flagcdn.com/cd.svg
//         flags2:https://flagcdn.com/w320/cd.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ck.svg
//         flags2:https://flagcdn.com/w320/ck.png
// httprequest.js:23 
//         flags:https://flagcdn.com/cr.svg
//         flags2:https://flagcdn.com/w320/cr.png
// httprequest.js:23 
//         flags:https://flagcdn.com/hr.svg
//         flags2:https://flagcdn.com/w320/hr.png
// httprequest.js:23 
//         flags:https://flagcdn.com/cu.svg
//         flags2:https://flagcdn.com/w320/cu.png
// httprequest.js:23 
//         flags:https://flagcdn.com/cw.svg
//         flags2:https://flagcdn.com/w320/cw.png
// httprequest.js:23 
//         flags:https://flagcdn.com/cy.svg
//         flags2:https://flagcdn.com/w320/cy.png
// httprequest.js:23 
//         flags:https://flagcdn.com/cz.svg
//         flags2:https://flagcdn.com/w320/cz.png
// httprequest.js:23 
//         flags:https://flagcdn.com/dk.svg
//         flags2:https://flagcdn.com/w320/dk.png
// httprequest.js:23 
//         flags:https://flagcdn.com/dj.svg
//         flags2:https://flagcdn.com/w320/dj.png
// httprequest.js:23 
//         flags:https://flagcdn.com/dm.svg
//         flags2:https://flagcdn.com/w320/dm.png
// httprequest.js:23 
//         flags:https://flagcdn.com/do.svg
//         flags2:https://flagcdn.com/w320/do.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ec.svg
//         flags2:https://flagcdn.com/w320/ec.png
// httprequest.js:23 
//         flags:https://flagcdn.com/eg.svg
//         flags2:https://flagcdn.com/w320/eg.png
// httprequest.js:23 
//         flags:https://flagcdn.com/sv.svg
//         flags2:https://flagcdn.com/w320/sv.png
// httprequest.js:23 
//         flags:https://flagcdn.com/gq.svg
//         flags2:https://flagcdn.com/w320/gq.png
// httprequest.js:23 
//         flags:https://flagcdn.com/er.svg
//         flags2:https://flagcdn.com/w320/er.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ee.svg
//         flags2:https://flagcdn.com/w320/ee.png
// httprequest.js:23 
//         flags:https://flagcdn.com/et.svg
//         flags2:https://flagcdn.com/w320/et.png
// httprequest.js:23 
//         flags:https://flagcdn.com/fk.svg
//         flags2:https://flagcdn.com/w320/fk.png
// httprequest.js:23 
//         flags:https://flagcdn.com/fo.svg
//         flags2:https://flagcdn.com/w320/fo.png
// httprequest.js:23 
//         flags:https://flagcdn.com/fj.svg
//         flags2:https://flagcdn.com/w320/fj.png
// httprequest.js:23 
//         flags:https://flagcdn.com/fi.svg
//         flags2:https://flagcdn.com/w320/fi.png
// httprequest.js:23 
//         flags:https://flagcdn.com/fr.svg
//         flags2:https://flagcdn.com/w320/fr.png
// httprequest.js:23 
//         flags:https://flagcdn.com/gf.svg
//         flags2:https://flagcdn.com/w320/gf.png
// httprequest.js:23 
//         flags:https://flagcdn.com/pf.svg
//         flags2:https://flagcdn.com/w320/pf.png
// httprequest.js:23 
//         flags:https://flagcdn.com/tf.svg
//         flags2:https://flagcdn.com/w320/tf.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ga.svg
//         flags2:https://flagcdn.com/w320/ga.png
// httprequest.js:23 
//         flags:https://flagcdn.com/gm.svg
//         flags2:https://flagcdn.com/w320/gm.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ge.svg
//         flags2:https://flagcdn.com/w320/ge.png
// httprequest.js:23 
//         flags:https://flagcdn.com/de.svg
//         flags2:https://flagcdn.com/w320/de.png
// httprequest.js:23 
//         flags:https://flagcdn.com/gh.svg
//         flags2:https://flagcdn.com/w320/gh.png
// httprequest.js:23 
//         flags:https://flagcdn.com/gi.svg
//         flags2:https://flagcdn.com/w320/gi.png
// httprequest.js:23 
//         flags:https://flagcdn.com/gr.svg
//         flags2:https://flagcdn.com/w320/gr.png
// httprequest.js:23 
//         flags:https://flagcdn.com/gl.svg
//         flags2:https://flagcdn.com/w320/gl.png
// httprequest.js:23 
//         flags:https://flagcdn.com/gd.svg
//         flags2:https://flagcdn.com/w320/gd.png
// httprequest.js:23 
//         flags:https://flagcdn.com/gp.svg
//         flags2:https://flagcdn.com/w320/gp.png
// httprequest.js:23 
//         flags:https://flagcdn.com/gu.svg
//         flags2:https://flagcdn.com/w320/gu.png
// httprequest.js:23 
//         flags:https://flagcdn.com/gt.svg
//         flags2:https://flagcdn.com/w320/gt.png
// httprequest.js:23 
//         flags:https://flagcdn.com/gg.svg
//         flags2:https://flagcdn.com/w320/gg.png
// httprequest.js:23 
//         flags:https://flagcdn.com/gn.svg
//         flags2:https://flagcdn.com/w320/gn.png
// httprequest.js:23 
//         flags:https://flagcdn.com/gw.svg
//         flags2:https://flagcdn.com/w320/gw.png
// httprequest.js:23 
//         flags:https://flagcdn.com/gy.svg
//         flags2:https://flagcdn.com/w320/gy.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ht.svg
//         flags2:https://flagcdn.com/w320/ht.png
// httprequest.js:23 
//         flags:https://flagcdn.com/hm.svg
//         flags2:https://flagcdn.com/w320/hm.png
// httprequest.js:23 
//         flags:https://flagcdn.com/va.svg
//         flags2:https://flagcdn.com/w320/va.png
// httprequest.js:23 
//         flags:https://flagcdn.com/hn.svg
//         flags2:https://flagcdn.com/w320/hn.png
// httprequest.js:23 
//         flags:https://flagcdn.com/hu.svg
//         flags2:https://flagcdn.com/w320/hu.png
// httprequest.js:23 
//         flags:https://flagcdn.com/hk.svg
//         flags2:https://flagcdn.com/w320/hk.png
// httprequest.js:23 
//         flags:https://flagcdn.com/is.svg
//         flags2:https://flagcdn.com/w320/is.png
// httprequest.js:23 
//         flags:https://flagcdn.com/in.svg
//         flags2:https://flagcdn.com/w320/in.png
// httprequest.js:23 
//         flags:https://flagcdn.com/id.svg
//         flags2:https://flagcdn.com/w320/id.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ci.svg
//         flags2:https://flagcdn.com/w320/ci.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ir.svg
//         flags2:https://flagcdn.com/w320/ir.png
// httprequest.js:23 
//         flags:https://flagcdn.com/iq.svg
//         flags2:https://flagcdn.com/w320/iq.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ie.svg
//         flags2:https://flagcdn.com/w320/ie.png
// httprequest.js:23 
//         flags:https://flagcdn.com/im.svg
//         flags2:https://flagcdn.com/w320/im.png
// httprequest.js:23 
//         flags:https://flagcdn.com/il.svg
//         flags2:https://flagcdn.com/w320/il.png
// httprequest.js:23 
//         flags:https://flagcdn.com/it.svg
//         flags2:https://flagcdn.com/w320/it.png
// httprequest.js:23 
//         flags:https://flagcdn.com/jm.svg
//         flags2:https://flagcdn.com/w320/jm.png
// httprequest.js:23 
//         flags:https://flagcdn.com/jp.svg
//         flags2:https://flagcdn.com/w320/jp.png
// httprequest.js:23 
//         flags:https://flagcdn.com/je.svg
//         flags2:https://flagcdn.com/w320/je.png
// httprequest.js:23 
//         flags:https://flagcdn.com/jo.svg
//         flags2:https://flagcdn.com/w320/jo.png
// httprequest.js:23 
//         flags:https://flagcdn.com/kz.svg
//         flags2:https://flagcdn.com/w320/kz.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ke.svg
//         flags2:https://flagcdn.com/w320/ke.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ki.svg
//         flags2:https://flagcdn.com/w320/ki.png
// httprequest.js:23 
//         flags:https://flagcdn.com/kw.svg
//         flags2:https://flagcdn.com/w320/kw.png
// httprequest.js:23 
//         flags:https://flagcdn.com/kg.svg
//         flags2:https://flagcdn.com/w320/kg.png
// httprequest.js:23 
//         flags:https://flagcdn.com/la.svg
//         flags2:https://flagcdn.com/w320/la.png
// httprequest.js:23 
//         flags:https://flagcdn.com/lv.svg
//         flags2:https://flagcdn.com/w320/lv.png
// httprequest.js:23 
//         flags:https://flagcdn.com/lb.svg
//         flags2:https://flagcdn.com/w320/lb.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ls.svg
//         flags2:https://flagcdn.com/w320/ls.png
// httprequest.js:23 
//         flags:https://flagcdn.com/lr.svg
//         flags2:https://flagcdn.com/w320/lr.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ly.svg
//         flags2:https://flagcdn.com/w320/ly.png
// httprequest.js:23 
//         flags:https://flagcdn.com/li.svg
//         flags2:https://flagcdn.com/w320/li.png
// httprequest.js:23 
//         flags:https://flagcdn.com/lt.svg
//         flags2:https://flagcdn.com/w320/lt.png
// httprequest.js:23 
//         flags:https://flagcdn.com/lu.svg
//         flags2:https://flagcdn.com/w320/lu.png
// httprequest.js:23 
//         flags:https://flagcdn.com/mo.svg
//         flags2:https://flagcdn.com/w320/mo.png
// httprequest.js:23 
//         flags:https://flagcdn.com/mk.svg
//         flags2:https://flagcdn.com/w320/mk.png
// httprequest.js:23 
//         flags:https://flagcdn.com/mg.svg
//         flags2:https://flagcdn.com/w320/mg.png
// httprequest.js:23 
//         flags:https://flagcdn.com/mw.svg
//         flags2:https://flagcdn.com/w320/mw.png
// httprequest.js:23 
//         flags:https://flagcdn.com/my.svg
//         flags2:https://flagcdn.com/w320/my.png
// httprequest.js:23 
//         flags:https://flagcdn.com/mv.svg
//         flags2:https://flagcdn.com/w320/mv.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ml.svg
//         flags2:https://flagcdn.com/w320/ml.png
// httprequest.js:23 
//         flags:https://flagcdn.com/mt.svg
//         flags2:https://flagcdn.com/w320/mt.png
// httprequest.js:23 
//         flags:https://flagcdn.com/mh.svg
//         flags2:https://flagcdn.com/w320/mh.png
// httprequest.js:23 
//         flags:https://flagcdn.com/mq.svg
//         flags2:https://flagcdn.com/w320/mq.png
// httprequest.js:23 
//         flags:https://flagcdn.com/mr.svg
//         flags2:https://flagcdn.com/w320/mr.png
// httprequest.js:23 
//         flags:https://flagcdn.com/mu.svg
//         flags2:https://flagcdn.com/w320/mu.png
// httprequest.js:23 
//         flags:https://flagcdn.com/yt.svg
//         flags2:https://flagcdn.com/w320/yt.png
// httprequest.js:23 
//         flags:https://flagcdn.com/mx.svg
//         flags2:https://flagcdn.com/w320/mx.png
// httprequest.js:23 
//         flags:https://flagcdn.com/fm.svg
//         flags2:https://flagcdn.com/w320/fm.png
// httprequest.js:23 
//         flags:https://flagcdn.com/md.svg
//         flags2:https://flagcdn.com/w320/md.png
// httprequest.js:23 
//         flags:https://flagcdn.com/mc.svg
//         flags2:https://flagcdn.com/w320/mc.png
// httprequest.js:23 
//         flags:https://flagcdn.com/mn.svg
//         flags2:https://flagcdn.com/w320/mn.png
// httprequest.js:23 
//         flags:https://flagcdn.com/me.svg
//         flags2:https://flagcdn.com/w320/me.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ms.svg
//         flags2:https://flagcdn.com/w320/ms.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ma.svg
//         flags2:https://flagcdn.com/w320/ma.png
// httprequest.js:23 
//         flags:https://flagcdn.com/mz.svg
//         flags2:https://flagcdn.com/w320/mz.png
// httprequest.js:23 
//         flags:https://flagcdn.com/mm.svg
//         flags2:https://flagcdn.com/w320/mm.png
// httprequest.js:23 
//         flags:https://flagcdn.com/na.svg
//         flags2:https://flagcdn.com/w320/na.png
// httprequest.js:23 
//         flags:https://flagcdn.com/nr.svg
//         flags2:https://flagcdn.com/w320/nr.png
// httprequest.js:23 
//         flags:https://flagcdn.com/np.svg
//         flags2:https://flagcdn.com/w320/np.png
// httprequest.js:23 
//         flags:https://flagcdn.com/nl.svg
//         flags2:https://flagcdn.com/w320/nl.png
// httprequest.js:23 
//         flags:https://flagcdn.com/nc.svg
//         flags2:https://flagcdn.com/w320/nc.png
// httprequest.js:23 
//         flags:https://flagcdn.com/nz.svg
//         flags2:https://flagcdn.com/w320/nz.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ni.svg
//         flags2:https://flagcdn.com/w320/ni.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ne.svg
//         flags2:https://flagcdn.com/w320/ne.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ng.svg
//         flags2:https://flagcdn.com/w320/ng.png
// httprequest.js:23 
//         flags:https://flagcdn.com/nu.svg
//         flags2:https://flagcdn.com/w320/nu.png
// httprequest.js:23 
//         flags:https://flagcdn.com/nf.svg
//         flags2:https://flagcdn.com/w320/nf.png
// httprequest.js:23 
//         flags:https://flagcdn.com/kp.svg
//         flags2:https://flagcdn.com/w320/kp.png
// httprequest.js:23 
//         flags:https://flagcdn.com/mp.svg
//         flags2:https://flagcdn.com/w320/mp.png
// httprequest.js:23 
//         flags:https://flagcdn.com/no.svg
//         flags2:https://flagcdn.com/w320/no.png
// httprequest.js:23 
//         flags:https://flagcdn.com/om.svg
//         flags2:https://flagcdn.com/w320/om.png
// httprequest.js:23 
//         flags:https://flagcdn.com/pk.svg
//         flags2:https://flagcdn.com/w320/pk.png
// httprequest.js:23 
//         flags:https://flagcdn.com/pw.svg
//         flags2:https://flagcdn.com/w320/pw.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ps.svg
//         flags2:https://flagcdn.com/w320/ps.png
// httprequest.js:23 
//         flags:https://flagcdn.com/pa.svg
//         flags2:https://flagcdn.com/w320/pa.png
// httprequest.js:23 
//         flags:https://flagcdn.com/pg.svg
//         flags2:https://flagcdn.com/w320/pg.png
// httprequest.js:23 
//         flags:https://flagcdn.com/py.svg
//         flags2:https://flagcdn.com/w320/py.png
// httprequest.js:23 
//         flags:https://flagcdn.com/pe.svg
//         flags2:https://flagcdn.com/w320/pe.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ph.svg
//         flags2:https://flagcdn.com/w320/ph.png
// httprequest.js:23 
//         flags:https://flagcdn.com/pn.svg
//         flags2:https://flagcdn.com/w320/pn.png
// httprequest.js:23 
//         flags:https://flagcdn.com/pl.svg
//         flags2:https://flagcdn.com/w320/pl.png
// httprequest.js:23 
//         flags:https://flagcdn.com/pt.svg
//         flags2:https://flagcdn.com/w320/pt.png
// httprequest.js:23 
//         flags:https://flagcdn.com/pr.svg
//         flags2:https://flagcdn.com/w320/pr.png
// httprequest.js:23 
//         flags:https://flagcdn.com/qa.svg
//         flags2:https://flagcdn.com/w320/qa.png
// httprequest.js:23 
//         flags:https://flagcdn.com/xk.svg
//         flags2:https://flagcdn.com/w320/xk.png
// httprequest.js:23 
//         flags:https://flagcdn.com/re.svg
//         flags2:https://flagcdn.com/w320/re.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ro.svg
//         flags2:https://flagcdn.com/w320/ro.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ru.svg
//         flags2:https://flagcdn.com/w320/ru.png
// httprequest.js:23 
//         flags:https://flagcdn.com/rw.svg
//         flags2:https://flagcdn.com/w320/rw.png
// httprequest.js:23 
//         flags:https://flagcdn.com/bl.svg
//         flags2:https://flagcdn.com/w320/bl.png
// httprequest.js:23 
//         flags:https://flagcdn.com/sh.svg
//         flags2:https://flagcdn.com/w320/sh.png
// httprequest.js:23 
//         flags:https://flagcdn.com/kn.svg
//         flags2:https://flagcdn.com/w320/kn.png
// httprequest.js:23 
//         flags:https://flagcdn.com/lc.svg
//         flags2:https://flagcdn.com/w320/lc.png
// httprequest.js:23 
//         flags:https://flagcdn.com/mf.svg
//         flags2:https://flagcdn.com/w320/mf.png
// httprequest.js:23 
//         flags:https://flagcdn.com/pm.svg
//         flags2:https://flagcdn.com/w320/pm.png
// httprequest.js:23 
//         flags:https://flagcdn.com/vc.svg
//         flags2:https://flagcdn.com/w320/vc.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ws.svg
//         flags2:https://flagcdn.com/w320/ws.png
// httprequest.js:23 
//         flags:https://flagcdn.com/sm.svg
//         flags2:https://flagcdn.com/w320/sm.png
// httprequest.js:23 
//         flags:https://flagcdn.com/st.svg
//         flags2:https://flagcdn.com/w320/st.png
// httprequest.js:23 
//         flags:https://flagcdn.com/sa.svg
//         flags2:https://flagcdn.com/w320/sa.png
// httprequest.js:23 
//         flags:https://flagcdn.com/sn.svg
//         flags2:https://flagcdn.com/w320/sn.png
// httprequest.js:23 
//         flags:https://flagcdn.com/rs.svg
//         flags2:https://flagcdn.com/w320/rs.png
// httprequest.js:23 
//         flags:https://flagcdn.com/sc.svg
//         flags2:https://flagcdn.com/w320/sc.png
// httprequest.js:23 
//         flags:https://flagcdn.com/sl.svg
//         flags2:https://flagcdn.com/w320/sl.png
// httprequest.js:23 
//         flags:https://flagcdn.com/sg.svg
//         flags2:https://flagcdn.com/w320/sg.png
// httprequest.js:23 
//         flags:https://flagcdn.com/sx.svg
//         flags2:https://flagcdn.com/w320/sx.png
// httprequest.js:23 
//         flags:https://flagcdn.com/sk.svg
//         flags2:https://flagcdn.com/w320/sk.png
// httprequest.js:23 
//         flags:https://flagcdn.com/si.svg
//         flags2:https://flagcdn.com/w320/si.png
// httprequest.js:23 
//         flags:https://flagcdn.com/sb.svg
//         flags2:https://flagcdn.com/w320/sb.png
// httprequest.js:23 
//         flags:https://flagcdn.com/so.svg
//         flags2:https://flagcdn.com/w320/so.png
// httprequest.js:23 
//         flags:https://flagcdn.com/za.svg
//         flags2:https://flagcdn.com/w320/za.png
// httprequest.js:23 
//         flags:https://flagcdn.com/gs.svg
//         flags2:https://flagcdn.com/w320/gs.png
// httprequest.js:23 
//         flags:https://flagcdn.com/kr.svg
//         flags2:https://flagcdn.com/w320/kr.png
// httprequest.js:23 
//         flags:https://flagcdn.com/es.svg
//         flags2:https://flagcdn.com/w320/es.png
// httprequest.js:23 
//         flags:https://flagcdn.com/lk.svg
//         flags2:https://flagcdn.com/w320/lk.png
// httprequest.js:23 
//         flags:https://flagcdn.com/sd.svg
//         flags2:https://flagcdn.com/w320/sd.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ss.svg
//         flags2:https://flagcdn.com/w320/ss.png
// httprequest.js:23 
//         flags:https://flagcdn.com/sr.svg
//         flags2:https://flagcdn.com/w320/sr.png
// httprequest.js:23 
//         flags:https://flagcdn.com/sj.svg
//         flags2:https://flagcdn.com/w320/sj.png
// httprequest.js:23 
//         flags:https://flagcdn.com/sz.svg
//         flags2:https://flagcdn.com/w320/sz.png
// httprequest.js:23 
//         flags:https://flagcdn.com/se.svg
//         flags2:https://flagcdn.com/w320/se.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ch.svg
//         flags2:https://flagcdn.com/w320/ch.png
// httprequest.js:23 
//         flags:https://flagcdn.com/sy.svg
//         flags2:https://flagcdn.com/w320/sy.png
// httprequest.js:23 
//         flags:https://flagcdn.com/tw.svg
//         flags2:https://flagcdn.com/w320/tw.png
// httprequest.js:23 
//         flags:https://flagcdn.com/tj.svg
//         flags2:https://flagcdn.com/w320/tj.png
// httprequest.js:23 
//         flags:https://flagcdn.com/tz.svg
//         flags2:https://flagcdn.com/w320/tz.png
// httprequest.js:23 
//         flags:https://flagcdn.com/th.svg
//         flags2:https://flagcdn.com/w320/th.png
// httprequest.js:23 
//         flags:https://flagcdn.com/tl.svg
//         flags2:https://flagcdn.com/w320/tl.png
// httprequest.js:23 
//         flags:https://flagcdn.com/tg.svg
//         flags2:https://flagcdn.com/w320/tg.png
// httprequest.js:23 
//         flags:https://flagcdn.com/tk.svg
//         flags2:https://flagcdn.com/w320/tk.png
// httprequest.js:23 
//         flags:https://flagcdn.com/to.svg
//         flags2:https://flagcdn.com/w320/to.png
// httprequest.js:23 
//         flags:https://flagcdn.com/tt.svg
//         flags2:https://flagcdn.com/w320/tt.png
// httprequest.js:23 
//         flags:https://flagcdn.com/tn.svg
//         flags2:https://flagcdn.com/w320/tn.png
// httprequest.js:23 
//         flags:https://flagcdn.com/tr.svg
//         flags2:https://flagcdn.com/w320/tr.png
// httprequest.js:23 
//         flags:https://flagcdn.com/tm.svg
//         flags2:https://flagcdn.com/w320/tm.png
// httprequest.js:23 
//         flags:https://flagcdn.com/tc.svg
//         flags2:https://flagcdn.com/w320/tc.png
// httprequest.js:23 
//         flags:https://flagcdn.com/tv.svg
//         flags2:https://flagcdn.com/w320/tv.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ug.svg
//         flags2:https://flagcdn.com/w320/ug.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ua.svg
//         flags2:https://flagcdn.com/w320/ua.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ae.svg
//         flags2:https://flagcdn.com/w320/ae.png
// httprequest.js:23 
//         flags:https://flagcdn.com/gb.svg
//         flags2:https://flagcdn.com/w320/gb.png
// httprequest.js:23 
//         flags:https://flagcdn.com/us.svg
//         flags2:https://flagcdn.com/w320/us.png
// httprequest.js:23 
//         flags:https://flagcdn.com/uy.svg
//         flags2:https://flagcdn.com/w320/uy.png
// httprequest.js:23 
//         flags:https://flagcdn.com/uz.svg
//         flags2:https://flagcdn.com/w320/uz.png
// httprequest.js:23 
//         flags:https://flagcdn.com/vu.svg
//         flags2:https://flagcdn.com/w320/vu.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ve.svg
//         flags2:https://flagcdn.com/w320/ve.png
// httprequest.js:23 
//         flags:https://flagcdn.com/vn.svg
//         flags2:https://flagcdn.com/w320/vn.png
// httprequest.js:23 
//         flags:https://flagcdn.com/wf.svg
//         flags2:https://flagcdn.com/w320/wf.png
// httprequest.js:23 
//         flags:https://flagcdn.com/eh.svg
//         flags2:https://flagcdn.com/w320/eh.png
// httprequest.js:23 
//         flags:https://flagcdn.com/ye.svg
//         flags2:https://flagcdn.com/w320/ye.png
// httprequest.js:23 
//         flags:https://flagcdn.com/zm.svg
//         flags2:https://flagcdn.com/w320/zm.png
// httprequest.js:23 
//         flags:https://flagcdn.com/zw.svg
//         flags2:https://flagcdn.com/w320/zw.png